name: enerf
channels:
  - anaconda
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.1.0
  - aiohttp=3.7.4.post0
  - appdirs=1.4.4
  - async-timeout=3.0.1
  - attrs=21.4.0
  - blas=1.0
  - blinker=1.4
  - blosc=1.21.0
  - blosc-hdf5-plugin=1.0.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.0.0
  - certifi=2022.6.15
  - cffi=1.15.0
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cloudpickle=1.6.0
  - commentjson=0.9.0
  - configargparse=1.5.3
  - cryptography=36.0.0
  - cudatoolkit=11.3.1
  - curl=7.80.0
  - cytoolz=0.11.0
  - dask-core=2.30.0
  - dbus=1.13.6
  - decorator=4.4.2
  - double-conversion=3.1.5
  - eigen=3.3.9
  - expat=2.2.10
  - ffmpeg=4.2.2
  - fontconfig=2.13.1
  - freetype=2.11.0
  - future=0.18.2
  - geos=3.8.0
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.7.0
  - google-auth-oauthlib=0.4.6
  - grpcio=1.42.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.16.1
  - imageio-ffmpeg=0.4.7
  - importlib-metadata=4.11.4
  - intel-openmp=2021.4.0
  - jpeg=9d
  - jsoncpp=1.9.4
  - jxrlib=1.1
  - kornia=0.6.4
  - krb5=1.19.2
  - lame=3.100
  - lark-parser=0.7.8
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=3.0
  - libaec=1.0.4
  - libcurl=7.80.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglu=9.0.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtheora=1.1.1
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvorbis=1.3.7
  - libvpx=1.7.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzopfli=1.0.3
  - loguru=0.5.3
  - lz4-c=1.9.3
  - markdown=3.3.7
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - ncurses=6.3
  - nettle=3.7.3
  - networkx=2.5
  - numpy=1.21.2
  - numpy-base=1.21.2
  - oauthlib=3.2.0
  - openh264=2.1.1
  - openjpeg=2.3.0
  - openssl=1.1.1q
  - packaging=21.3
  - pcre=8.45
  - pillow=9.0.1
  - pip=21.2.4
  - proj=6.2.1
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyglet=1.5.16
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pysocks=1.7.1
  - python=3.9.7
  - python_abi=3.9
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pyvista=0.33.3
  - pywavelets=1.3.0
  - pyyaml=5.4.1
  - qt=5.9.7
  - readline=8.1.2
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - scikit-image=0.19.2
  - scipy=1.7.3
  - scooby=0.5.12
  - setuptools=58.0.4
  - shapely=1.7.1
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.38.0
  - tbb=2021.5.0
  - tensorboard=2.9.1
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tifffile=2020.10.1
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.1
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.8
  - utfcpp=3.2.1
  - vtk=9.0.3
  - werkzeug=2.1.2
  - wheel=0.37.1
  - x264=1!157.20191217
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zfp=0.5.5
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - alabaster==0.7.12
    - anyio==3.6.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - babel==2.10.1
    - backcall==0.2.0
    - bagpy==0.4.10
    - beautifulsoup4==4.11.1
    - bitstring==3.1.9
    - bleach==5.0.1
    - blobfile==1.3.3
    - catkin-pkg==0.5.2
    - commonmark==0.9.1
    - cycler==0.11.0
    - dall-e==0.1
    - dearpygui==1.4.0
    - debugpy==1.6.1
    - defusedxml==0.7.1
    - distro==1.7.0
    - docutils==0.17.1
    - einops==0.4.1
    - entrypoints==0.4
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - filelock==3.8.0
    - fonttools==4.30.0
    - ghp-import==2.1.0
    - gnupg==2.3.1
    - guppy3==3.1.2
    - h5py==3.7.0
    - hdf5plugin==3.3.1
    - imagesize==1.3.0
    - iniconfig==1.1.1
    - ipykernel==6.15.0
    - ipympl==0.9.1
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.1
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - json5==0.9.8
    - jsonschema==4.6.2
    - jupyter-client==7.3.4
    - jupyter-core==4.11.0
    - jupyter-server==1.18.1
    - jupyterlab==3.4.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.15.0
    - jupyterlab-widgets==1.1.1
    - kiwisolver==1.3.2
    - llvmlite==0.38.1
    - lpips==0.1.4
    - lz4==4.0.1
    - m2r2==0.3.2
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mergedeep==1.3.4
    - mistune==0.8.4
    - mkdocs==1.3.0
    - mypy==0.971
    - mypy-extensions==0.4.3
    - natsort==8.1.0
    - nbclassic==0.4.2
    - nbclient==0.6.6
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - ninja==1.10.2.3
    - notebook==6.4.12
    - notebook-shim==0.1.0
    - numba==0.55.2
    - opencv-python==4.5.5.64
    - pandas==1.4.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pluggy==1.0.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - protobuf==3.19.4
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py==1.11.0
    - py3rosmsgs==1.18.2
    - pycryptodomex==3.14.1
    - pydash==5.1.0
    - pygments==2.11.2
    - pymcubes==0.1.2
    - pymdown-extensions==9.5
    - pyrsistent==0.18.1
    - pysdf==0.1.8
    - pyserial==3.5
    - pytest==7.1.2
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml-env-tag==0.1
    - pyzmq==23.2.0
    - recommonmark==0.7.1
    - rich==12.0.0
    - rinoh-typeface-dejavuserif==0.1.3
    - rinoh-typeface-texgyrecursor==0.1.1
    - rinoh-typeface-texgyreheros==0.1.1
    - rinoh-typeface-texgyrepagella==0.1.1
    - rinohtype==0.5.3
    - rospkg==1.4.0
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - scikit-learn==1.1.1
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sniffio==1.2.0
    - snowballstemmer==2.2.0
    - soupsieve==2.3.2.post1
    - sphinx==3.2.1
    - sphinx-autodoc-typehints==1.4.0
    - sphinx-bootstrap-theme==0.8.1
    - sphinx-markdown-parser==0.2.4
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - stack-data==0.2.0
    - tensorboardx==2.5
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - timm==0.6.7
    - tinycss2==1.1.1
    - tomli==2.0.1
    - torch-ema==0.3
    - tornado==6.2
    - tqdm==4.63.0
    - traitlets==5.2.2.post1
    - trimesh==3.10.2
    - unify==0.5
    - untokenize==0.1.1
    - watchdog==2.1.8
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.3
    - widgetsnbextension==3.6.1
    - xmltodict==0.12.0
    - yapf==0.32.0
    - ytsphinx==1.2.1.dev20200430
    - zstandard==0.17.0
